export default {
  LOGIN: "/login",
  SalesHome: "/sales-home",
  SALESHOME: "/sales",
  DELIVERYHOME: "/delivery",
  // SALESHOMEOPTION: "/home",
  // DELIVERYHOMEOPTION: "/home",
  VIDEO: "/how-to-use",
  CONTACT: "/contact-us",
  CHANGEPASSWORD :"/change-password",
  MYPROJECTS: "/my-deals",
  DEMOPROJECT: "/demo-project",
  NEWPROJECT: '/new-deal',
  MASTEROFFERING: '/create-master',
  // PROJECT: '/deal',
  VALUEDRIVERS: '/value-drivers',
  BUSINESSCASE: '/business-case',
  MANUALLYSELECTKPIS: '/manually-select-kpis',
  REVIEWVALUEDRIVERTREE: '/review-value-driver-tree',
  ADDINITIATIVEINFORMATION: '/add-initiative-infomation',
  SETKPITARGET: '/set-kpi-targets',
  PUBLISHDASHBOARD: '/publish-dashboards',
  HOME: '/',
  LANDING: '/home',
  ADMINPANEL: '/admin',
  OPPORTUNITYREQUEST:'/admin/opportunity-requests',
  CLIENTMASTER: '/admin/client-master-home',
  ACCESSCONTROL: '/admin/access-control',
  ACCESSMANAGEMENT: '/admin/access-management',
  UPLOADVALUEDRIVER: '/admin/upload-vdt-elements',
  CAPTUREACTUALS: '/capture-actuals',
  DASHBOARD_VALUE_ARCH: '/dashboards-value-arch',
  DASHBOARD_VALUE_TRACKING: '/dashboards-value-tracking',
  FULLSCREENVDT: '/full-screen-view',
  DEFINEWORKSTREAM: '/workstream-home',
  NOMATCH: "*",
  ALLOWED: [
    "/login",
    "/",
    "/description-page",
    // "/home",
    "/how-to-use",
    "/contact-us",
    "/my-deals",
    "/demo-project",
    "/new-deal",
    // '/deal',
    "/value-drivers",
    '/business-case',
    '/manually-select-kpis',
    '/add-initiative-infomation',
    '/set-kpi-targets',
    '/publish-dashboards',
    '/sales',
    '/delivery',
    '/admin',
    '/admin/client-master-home',
    '/admin/access-control',
    '/admin/access-management',
    '/admin/upload-vdt-elements',
    '/admin/opportunity-requests',
    '/capture-actuals',
    '/full-screen-view'
  ]
};
